<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added' => 'Дата добавления',
    'Balance' => 'Баланс',
    'Partner Balance' => 'Партнерский баланс',
    'Balance change' => 'Измнение баланса',
    'Body' => 'Сообщение',
    'Comment' => 'Комментарий',
    'Company' => 'Компания',
    'Data Json' => '',
    'E-mail' => 'Email',
    'Enable Partner Payments' => 'Включить выплаты',
    'From invited User ID' => 'От привлеченного клиента',
    'ID' => 'ID',
    'Incorrect E-mail or password.' => 'Неправильный E-mail или пароль.',
    'Invited By User ID' => 'Приглашен пользователм',
    'Is Admin' => 'Администратор?',
    'Is Common' => 'Общая?',
    'Is Partner' => 'Партнер?',
    'Is Service Paused' => 'Сервис приостановлен',
    'Is real money' => 'Реальные деньги',
    'Last Login Ip' => 'Последний IP входа',
    'Name' => 'Имя',
    'New password' => 'Новый пароль',
    'Paid Until Date Time' => 'Оплачено до',
    'Parent transaction ID' => '',
    'Partner' => 'Партнер',
    'Partner Earned' => 'Заработано',
    'Partner Percent' => 'Процент',
    'Password' => 'Пароль',
    'Password Changed Date Time' => 'Дата изменения пароля',
    'Register Ip' => 'IP регистрации',
    'Restore Password Key' => '',
    'Restore Password Until Date' => '',
    'Site' => 'Сайт',
    'Telephone' => 'Телефон',
    'Timezone' => 'Часовой пояс',
    'Topic' => 'Тема',
    'Updated Date Time' => 'Обновить время',
    'User ID' => 'ID пользователя',
    'WMR' => 'WMR',
    'Wrong link to reset the password.' => 'Неверная ссылка для восстановления пароля.',
];
