version: "3.8"
services:
  db:
    #image: postgres:12-alpine
    image: groonga/pgroonga:latest-alpine-12-slim
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-trust}
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./:/app:delegated
    ports:
      - "${LISTEN_HOST:-127.0.0.1}:${POSTGRES_PORT:-5432}:5432"

  web:
    build:
      context: ./docker/web
      target: "dev"
      args:
        BASE_IMAGE: "php-nginx-dev"
    ports:
      - "${LISTEN_HOST:-127.0.0.1}:${HTTP_PORT:-80}:80"
      - "${LISTEN_HOST:-127.0.0.1}:${HTTPS_PORT:-443}:80"
    volumes:
      - composer-cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/web/nginx/vhost.conf:/opt/docker/etc/nginx/vhost.conf
      - ./docker/web/nginx/vhost-dev.conf:/opt/docker/etc/nginx/vhost-dev.conf
      - ./docker/web/php/php.ini:/opt/docker/etc/php/php.ini
      - ./docker/web/supervisord/postfix.conf:/opt/docker/etc/supervisor.d/postfix.conf
      - ./docker/web/supervisord/juman.conf:/opt/docker/etc/supervisor.d/juman.conf
      - ./docker/web/entrypoint.sh:/opt/docker/bin/entrypoint.d/app.sh
      - node-modules:${NODE_MODULES_MOUNT:-/app/frontend/node_modules}
      - node-modules-backend:${NODE_MODULES_BACKEND_MOUNT:-/app/backend-ts/node_modules}
      - npm-cache:/root/.npm
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_DEBUGGER=xdebug
      - DISABLE_BEFORE_START_PROD=1
    # Can be activated when docker-compose will support "host-gateway" value
    # Currently:
    # on Windows and macOS host.docker.internal added automatically by Docker Desktop
    # on Linux host.docker.internal added in entrypoint.sh
    #extra_hosts:
    #  - host.docker.internal:host-gateway

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 0
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 0
      GUNICORN_ACCESS_LOGFILE: /dev/null
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/.pgpass:/pgadmin4/.pgpass
    ports:
      - "${LISTEN_HOST:-127.0.0.1}:${PGADMIN_PORT:-5001}:80"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${LISTEN_HOST:-127.0.0.1}:${ADMINER_PORT:-5002}:8080"

volumes:
  db-data:
  pgadmin:
  composer-cache:
  npm-cache:
  node-modules:
  node-modules-backend:
