import { Component, OnInit } from '@angular/core';

import { RadSideDrawer } from 'nativescript-ui-sidedrawer';
import * as app from 'tns-core-modules/application';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.tns.html',
  styleUrls: ['./auto-generated.component.tns.css']
})
export class AutoGeneratedComponent implements OnInit {
  constructor() { }

  ngOnInit() {
  }

  onDrawerButtonTap(): void {
    const sideDrawer = <RadSideDrawer>app.getRootView();
    sideDrawer.showDrawer();
  }
}
