import { Component, OnInit } from '@angular/core';
import { RadSideDrawer } from 'nativescript-ui-sidedrawer';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.tns.html',
  styleUrls: ['./auto-generated.component.tns.css']
})
export class AutoGeneratedComponent implements OnInit {
  constructor() { }

  ngOnInit() {
  }

   onDrawerButtonTap(): void {
  //  const sideDrawer = <RadSideDrawer>.getRootView();
  //  sideDrawer.showDrawer();
   }
}
