apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: langapp
  name: langapp-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: langapp
  name: langapp
  labels:
    app: langapp
spec:
  selector:
    matchLabels:
      app: langapp
  template:
    metadata:
      labels:
        app: langapp
    spec:
      volumes:
        - name: langapp-uploads-pv
          persistentVolumeClaim:
            claimName: langapp-uploads-pvc
      containers:
        - name: langapp
          image: langapp-image
          ports:
            - name: http
              containerPort: 80
          env:
            - name: PGHOST
              value: acid-langapp-cluster
            - name: PGDATABASE
              value: langapp
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: langapp.acid-langapp-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: langapp.acid-langapp-cluster.credentials.postgresql.acid.zalan.do
                  key: password
          volumeMounts:
            - mountPath: /app/backend/web/uploads
              name: langapp-uploads-pv
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "8192Mi"
              cpu: "32000m"
